# Generated by Django 6.1.1 on 2026-09-12 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaboration", "0001_initial"),
        ("core", "0001_initial"),
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentationpage",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="pageclipitem",
            name="clip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_items",
                to="media.clip",
            ),
        ),
        migrations.AddField(
            model_name="pageclipitem",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clip_items",
                to="collaboration.documentationpage",
            ),
        ),
        migrations.AddField(
            model_name="documentationpage",
            name="clips",
            field=models.ManyToManyField(
                related_name="documentation_pages",
                through="collaboration.PageClipItem",
                to="media.clip",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playlistitem",
            name="clip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlist_items",
                to="media.clip",
            ),
        ),
        migrations.AddField(
            model_name="playlistitem",
            name="playlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="collaboration.playlist",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="clips",
            field=models.ManyToManyField(
                related_name="playlists",
                through="collaboration.PlaylistItem",
                to="media.clip",
            ),
        ),
        migrations.AddField(
            model_name="stepguide",
            name="clip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="step_guides",
                to="media.clip",
            ),
        ),
        migrations.AddConstraint(
            model_name="pageclipitem",
            constraint=models.UniqueConstraint(
                fields=("page", "clip"), name="uniq_clip_per_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentationpage",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="uniq_page_slug_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistitem",
            constraint=models.UniqueConstraint(
                fields=("playlist", "clip"), name="uniq_clip_per_playlist"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["organization", "visibility"],
                name="apc_playlis_organiz_8eea1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stepguide",
            constraint=models.UniqueConstraint(
                fields=("clip", "step_number"), name="uniq_step_number_per_clip"
            ),
        ),
    ]
