# Generated by Django 6.1.1 on 2026-09-13 13:35

from django.db import migrations, models


def resequence_positions(apps, schema_editor):
    """Existing rows predate server-assigned positions and can collide (every
    item defaulted to 0) — renumber each playlist's items by `added_at` before
    the unique constraint below would otherwise fail to apply."""
    PlaylistItem = apps.get_model("collaboration", "PlaylistItem")
    playlist_ids = PlaylistItem.objects.values_list("playlist_id", flat=True).distinct()
    for playlist_id in playlist_ids:
        items = PlaylistItem.objects.filter(playlist_id=playlist_id).order_by("position", "added_at")
        for index, item in enumerate(items):
            if item.position != index:
                item.position = index
                item.save(update_fields=["position"])


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_initial"),
        ("media", "0004_clip_filter_settings"),
    ]

    operations = [
        migrations.RunPython(resequence_positions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="playlistitem",
            constraint=models.UniqueConstraint(
                fields=("playlist", "position"), name="uniq_position_per_playlist"
            ),
        ),
    ]
