"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_list(key, default=""):
    raw = os.getenv(key, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-oxfzp=8f+)@6iw)qjhk-o^(0*iaov21nd&xc*37%f-u%!*w%*5")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "core",
    "media",
    "studio",
    "collaboration",
    "sharing",
]

AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", "http://localhost:3000")
CORS_ALLOW_CREDENTIALS = True
# `Range` isn't one of the CORS "simple" headers and isn't in django-cors-headers'
# own default allowlist — a <video crossOrigin="use-credentials"> element's
# byte-range seek request is a credentialed cross-origin request that
# triggers a real preflight, and without `range` explicitly allowed here that
# preflight fails, silently blocking every seek (and, in browsers that probe
# with an early range request on initial load, blocking playback outright).
from corsheaders.defaults import default_headers  # noqa: E402

CORS_ALLOW_HEADERS = [*default_headers, "range"]
# Not required for a <video> tag itself (the browser's media engine reads
# these natively), but exposes them to any `fetch`/XHR-based consumer too.
CORS_EXPOSE_HEADERS = ["content-range", "accept-ranges", "content-length"]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "smart_onboarding"),
        "USER": os.getenv("DB_USER", "onboarding_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "onboarding_pass"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "3306"),
        # Persistent connections instead of reconnecting per-request.
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Local-disk media storage for recorded clips/thumbnails uploaded from the
# Studio editor. A real deployment would swap this for S3/GCS-backed storage
# behind a CDN, but local disk is sufficient for development.
MEDIA_URL = "/media/"
# Named "mediafiles", not "media" — the `media` Django app already owns that path.
MEDIA_ROOT = BASE_DIR / "mediafiles"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        [
            "rest_framework.renderers.JSONRenderer",
            "rest_framework.renderers.BrowsableAPIRenderer",
        ]
        if DEBUG
        else ["rest_framework.renderers.JSONRenderer"]
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "core.authentication.CookieJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# djangorestframework-simplejwt
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Cookie transport for JWTs, used by CookieJWTAuthentication and the
# core.views login/refresh/logout endpoints. Keeps tokens out of client-side
# JS (HttpOnly) while still working with the Next.js frontend on a
# different origin during local development.
JWT_AUTH_COOKIE = os.getenv("JWT_AUTH_COOKIE", "apc_access_token")
JWT_AUTH_REFRESH_COOKIE = os.getenv("JWT_AUTH_REFRESH_COOKIE", "apc_refresh_token")
JWT_COOKIE_SECURE = os.getenv("JWT_COOKIE_SECURE", "" if DEBUG else "True") == "True"
JWT_COOKIE_SAMESITE = os.getenv("JWT_COOKIE_SAMESITE", "Lax")


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Console backend prints outgoing mail (invitation links, etc.) to the
# server log instead of actually sending it — swap EMAIL_BACKEND for a real
# SMTP/SES/etc. backend, and set the SMTP_* vars below, once there's a
# provider to send through.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "APC <no-reply@apc.local>")

# Base URL of the Next.js frontend, used to build links embedded in emails
# (e.g. the workspace-invitation accept link) — the backend has no other way
# to know where the frontend is deployed.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")


# Celery — async pipeline for the AI Auto-Edit & Voiceover workflow
# (studio/tasks.py). Redis doubles as broker and result backend since
# there's no other queue/cache in this stack yet to separate them onto.
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Custom phase states (studio/tasks.py's `self.update_state(state="TRANSCRIBING", ...)`
# etc.) aren't in Celery's built-in READY_STATES, so without this a result
# backend configured to expire never clears them — same TTL Celery's own
# built-in states get by default.
CELERY_RESULT_EXPIRES = int(os.getenv("CELERY_RESULT_EXPIRES", str(60 * 60 * 24)))

# studio/services/handlers.py: local model endpoints for the AI Auto-Edit pipeline.
# AI_AUTO_EDIT_USE_MOCK defaults to True because this stack doesn't actually
# run Ollama (or Whisper/TTS) anywhere yet — see that module's docstring.
AI_AUTO_EDIT_USE_MOCK = os.getenv("AI_AUTO_EDIT_USE_MOCK", "True") == "True"
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://ollama:11434")
