# Generated by Django 6.1.1 on 2026-09-13 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workspacemembership_is_authorized_and_more"),
        ("sharing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("content_shared", "Content Shared"),
                            ("request_created", "Request Created"),
                            ("request_resolved", "Request Resolved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "apc_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="apc_notific_recipie_f4174f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedContent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("clip", "Clip"), ("playlist", "Playlist")],
                        max_length=20,
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "Can View"),
                            ("comment", "Can View & Comment"),
                            ("edit", "Can Edit"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_content",
                        to="core.organization",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_shared_with_department",
                        to="core.department",
                    ),
                ),
                (
                    "target_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_shared_with_team",
                        to="core.team",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "apc_shared_content",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="apc_shared__organiz_2ebf1f_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="apc_shared__content_307c7b_idx",
                    ),
                ],
            },
        ),
    ]
