# Generated by Django 6.1.1 on 2026-09-13 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_settings_user_avatar'),
        ('sharing', '0002_notification_sharedcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcontent',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='can_reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='can_reshare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='parent_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downstream_shares', to='sharing.sharedcontent'),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sharedcontent',
            index=models.Index(fields=['content_type', 'object_id', 'is_active'], name='apc_shared__content_9bc6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedcontent',
            index=models.Index(fields=['shared_by', 'is_active'], name='apc_shared__shared__cb77cb_idx'),
        ),
    ]
