# Generated by Django 6.1.1 on 2026-09-12 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineTrack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "track_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("zoom", "Zoom"),
                            ("blur", "Blur"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="media.clip",
                    ),
                ),
            ],
            options={
                "db_table": "apc_timeline_tracks",
                "ordering": ["clip", "order"],
            },
        ),
        migrations.CreateModel(
            name="TextOverlay",
            fields=[
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("position_x", models.DecimalField(decimal_places=2, max_digits=5)),
                ("position_y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("font_size", models.PositiveSmallIntegerField(default=24)),
                ("color", models.CharField(default="#FFFFFF", max_length=20)),
                ("background_color", models.CharField(blank=True, max_length=20)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_overlays",
                        to="studio.timelinetrack",
                    ),
                ),
            ],
            options={
                "db_table": "apc_text_overlays",
                "ordering": ["track", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BlurRegion",
            fields=[
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.DecimalField(decimal_places=2, max_digits=5)),
                ("y", models.DecimalField(decimal_places=2, max_digits=5)),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "shape",
                    models.CharField(
                        choices=[("rectangle", "Rectangle"), ("ellipse", "Ellipse")],
                        default="rectangle",
                        max_length=20,
                    ),
                ),
                ("blur_radius", models.PositiveSmallIntegerField(default=10)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blur_regions",
                        to="studio.timelinetrack",
                    ),
                ),
            ],
            options={
                "db_table": "apc_blur_regions",
                "ordering": ["track", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ZoomRegion",
            fields=[
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bounding box x, percent of frame width",
                        max_digits=5,
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bounding box y, percent of frame height",
                        max_digits=5,
                    ),
                ),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                ("height", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "scale_factor",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_regions",
                        to="studio.timelinetrack",
                    ),
                ),
            ],
            options={
                "db_table": "apc_zoom_regions",
                "ordering": ["track", "start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="timelinetrack",
            constraint=models.UniqueConstraint(
                fields=("clip", "order"), name="uniq_track_order_per_clip"
            ),
        ),
    ]
