# Generated by Django 6.1.1 on 2026-09-13 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinetrack",
            name="track_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("zoom", "Zoom"),
                    ("blur", "Blur"),
                    ("text", "Text"),
                    ("cut", "Cut"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Cut",
            fields=[
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cut_type",
                    models.CharField(
                        choices=[
                            ("keep", "Keep"),
                            ("cut", "Cut"),
                            ("silence_speedup", "Silence speedup"),
                        ],
                        default="cut",
                        max_length=20,
                    ),
                ),
                (
                    "speed_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuts",
                        to="studio.timelinetrack",
                    ),
                ),
            ],
            options={
                "db_table": "apc_cuts",
                "ordering": ["track", "start_time"],
            },
        ),
    ]
