# Generated by Django 6.1.1 on 2026-09-14 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_timelinetrack_track_type_cut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('start_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField(blank=True)),
                ('script_text', models.TextField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='studio.timelinetrack')),
            ],
            options={
                'db_table': 'apc_transcript_segments',
                'ordering': ['track', 'start_time'],
            },
        ),
    ]
