# Generated by Django 6.1.1 on 2026-09-12 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "duration_seconds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("private", "Private"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "apc_clips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("thumbnail", "Thumbnail"),
                            ("caption", "Caption"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(help_text="CDN/S3 URL of the stored asset"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=80)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "resolution",
                    models.CharField(
                        blank=True, help_text="e.g. 1920x1080", max_length=20
                    ),
                ),
                (
                    "framerate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="media.clip",
                    ),
                ),
            ],
            options={
                "db_table": "apc_clip_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["organization", "visibility"],
                name="apc_clips_organiz_96c7a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(fields=["author"], name="apc_clips_author__a11be0_idx"),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(fields=["status"], name="apc_clips_status_9abadc_idx"),
        ),
        migrations.AddConstraint(
            model_name="clip",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="uniq_clip_slug_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["clip", "asset_type"], name="apc_clip_as_clip_id_8fd78e_idx"
            ),
        ),
    ]
