# Generated by Django 6.1.1 on 2026-09-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="clip-thumbnails/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="clip-assets/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="clip",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="External thumbnail URL, used when no file is uploaded.",
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="file_url",
            field=models.URLField(
                blank=True,
                help_text="External CDN/S3 URL, used when no file is uploaded.",
            ),
        ),
    ]
