# Hand-written (not autogenerated): the `organization` FK is added as
# non-nullable directly since `apc_clip_assets` has zero rows in every
# environment this migration will run against pre-release — safe to apply
# without a placeholder default, which the interactive makemigrations
# questioner has no way to express for a ForeignKey anyway.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workspacemembership_is_authorized_and_more"),
        ("media", "0002_clip_thumbnail_mediaasset_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("thumbnail", "Thumbnail"),
                    ("caption", "Caption"),
                    ("overlay", "Overlay"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="clip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="media.clip",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_assets",
                to="core.organization",
                default=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_media_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="title",
            field=models.CharField(blank=True, max_length=255, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="duration",
            field=models.FloatField(default=0.0, help_text="Duration in seconds, for video/audio assets."),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(fields=["organization", "asset_type"], name="apc_clip_as_organiz_0698dc_idx"),
        ),
    ]
