# Generated by Django 6.1.1 on 2026-09-13 13:04

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_mediaasset_workspace_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="filter_settings",
            field=models.JSONField(
                blank=True, default=media.models.default_filter_settings
            ),
        ),
    ]
