import type { ClipItem, PageItem } from "@/types/library";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

export const MOCK_CLIPS: ClipItem[] = [
  {
    id: "clip-1",
    title: "Welcome to APC! 🚀",
    durationSeconds: 73,
    status: "published",
    createdAt: hoursAgo(240),
    updatedAt: hoursAgo(0.13),
    views: 214,
    likes: 18,
    comments: 4,
  },
  {
    id: "clip-2",
    title: "Clip on Sep 12, 2026 at 01:45 PM",
    durationSeconds: 0,
    status: "draft",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    views: 0,
    likes: 0,
    comments: 0,
  },
  {
    id: "clip-3",
    title: "Onboarding walkthrough — new hire setup",
    durationSeconds: 312,
    status: "published",
    createdAt: hoursAgo(96),
    updatedAt: hoursAgo(18),
    views: 87,
    likes: 9,
    comments: 2,
  },
  {
    id: "clip-4",
    title: "Q3 sales demo — objection handling",
    durationSeconds: 184,
    status: "draft",
    createdAt: hoursAgo(48),
    updatedAt: hoursAgo(30),
    views: 3,
    likes: 0,
    comments: 0,
  },
  {
    id: "clip-5",
    title: "How to submit an expense report",
    durationSeconds: 96,
    status: "published",
    createdAt: hoursAgo(500),
    updatedAt: hoursAgo(120),
    views: 342,
    likes: 41,
    comments: 11,
  },
  {
    id: "clip-6",
    title: "Engineering onboarding: repo access",
    durationSeconds: 421,
    status: "published",
    createdAt: hoursAgo(720),
    updatedAt: hoursAgo(200),
    views: 156,
    likes: 22,
    comments: 6,
  },
];

export const MOCK_PAGES: PageItem[] = [
  {
    id: "page-1",
    title: "My first page",
    status: "draft",
    createdAt: hoursAgo(0.4),
    updatedAt: hoursAgo(0.13),
    views: 0,
    sectionCount: 1,
  },
  {
    id: "page-2",
    title: "Page on Sep 12, 2026 at 01:45 PM",
    status: "draft",
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    views: 0,
    sectionCount: 2,
  },
  {
    id: "page-3",
    title: "New hire onboarding checklist",
    status: "published",
    createdAt: hoursAgo(400),
    updatedAt: hoursAgo(72),
    views: 128,
    sectionCount: 5,
  },
  {
    id: "page-4",
    title: "Support team runbook",
    status: "published",
    createdAt: hoursAgo(1200),
    updatedAt: hoursAgo(300),
    views: 64,
    sectionCount: 3,
  },
  {
    id: "page-5",
    title: "Q3 product roadmap overview",
    status: "draft",
    createdAt: hoursAgo(60),
    updatedAt: hoursAgo(40),
    views: 5,
    sectionCount: 4,
  },
];
