# Generated by Django 6.1.1 on 2026-09-13 00:21

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_language_user_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="is_authorized",
            field=models.BooleanField(
                default=True,
                help_text="Platform access. False effectively suspends the user.",
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Free-form organizational tags, e.g. 'Engineering'.",
            ),
        ),
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "token",
                    models.CharField(
                        default=core.models.generate_invitation_token,
                        editable=False,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_authorized", models.BooleanField(default=True)),
                ("is_creator", models.BooleanField(default=True)),
                ("is_global_admin", models.BooleanField(default=False)),
                ("is_content_manager", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(default=core.models.default_invitation_expiry),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.organization",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.team",
                    ),
                ),
            ],
            options={
                "db_table": "apc_workspace_invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="apc_workspa_token_60e207_idx"),
                    models.Index(
                        fields=["organization", "email"],
                        name="apc_workspa_organiz_799646_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "email", "status"),
                        name="uniq_pending_invite_per_email",
                    )
                ],
            },
        ),
    ]
