# Generated by Django 6.1.1 on 2026-09-13 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_role_tier(apps, schema_editor):
    """role_tier defaulted to 'creator' for every existing row above — give
    existing global admins and each organization's actual owner their
    correct tier instead of leaving them misclassified as plain creators."""
    WorkspaceMembership = apps.get_model("core", "WorkspaceMembership")
    for membership in WorkspaceMembership.objects.select_related("user", "organization"):
        if membership.organization.owner_id == membership.user_id:
            membership.role_tier = "owner"
        elif membership.is_global_admin:
            membership.role_tier = "global_admin"
        elif membership.is_creator:
            membership.role_tier = "creator"
        else:
            membership.role_tier = "viewer"
        membership.save(update_fields=["role_tier"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workspacemembership_is_authorized_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="role_tier",
            field=models.CharField(
                choices=[
                    ("owner", "Workspace Owner"),
                    ("global_admin", "Global Administrator"),
                    ("hr_manager", "HR Manager"),
                    ("project_manager", "Project Manager"),
                    ("team_lead", "Team Lead"),
                    ("creator", "Creator"),
                    ("viewer", "Viewer"),
                    ("custom", "Custom Defined Role"),
                ],
                default="creator",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("can_invite_users", models.BooleanField(default=False)),
                ("can_manage_departments", models.BooleanField(default=False)),
                ("can_manage_teams", models.BooleanField(default=False)),
                ("can_assign_roles", models.BooleanField(default=False)),
                ("can_publish_public_clips", models.BooleanField(default=False)),
                ("can_manage_playlists", models.BooleanField(default=False)),
                ("can_approve_requests", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("can_revoke_access", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoped_custom_roles",
                        to="core.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "apc_custom_roles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="custom_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_members",
                to="core.customrole",
            ),
        ),
        migrations.AddConstraint(
            model_name="customrole",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uniq_custom_role_per_org"
            ),
        ),
        migrations.RunPython(backfill_role_tier, migrations.RunPython.noop),
    ]
