# Generated by Django 6.1.1 on 2026-09-13 15:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_workspacemembership_revoked_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="settings",
            field=models.JSONField(
                blank=True, default=core.models.default_workspace_settings
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/%d/"
            ),
        ),
    ]
